
facility: facility.cpp
	c++ -O2 facility.cpp -o facility -I$GUROBI_HOME/include -L$GUROBI_HOME/lib/ -lgurobi_c++ -lgurobi81

facility_coek: facility_coek.cpp
	c++ -std=c++11 -O2 facility_coek.cpp -o facility_coek -I${COEK_HOME}/include -L${COEK_HOME}/lib/ -lcoek

