all:
	- cd knapsack; make
	- cd nqueens; make
	- cd pmedian; make

gurobi:
	- cd knapsack; make gurobi
	- cd nqueens; make gurobi
	- cd pmedian; make gurobi

coek:
	- cd knapsack; make coek
	- cd nqueens; make coek
	- cd pmedian; make coek

clean:
	- cd knapsack; make clean; cd ..
	- cd nqueens; make clean; cd ..
	- cd pmedian; make clean; cd ..
