
lqcp: lqcp.cpp
	c++ -O2 lqcp.cpp -o lqcp -I$GUROBI_HOME/include -L$GUROBI_HOME/lib/ -lgurobi_c++ -lgurobi81

lqcp_coek: lqcp_coek.cpp
	c++ -std=c++11 -O2 lqcp_coek.cpp -o lqcp_coek -I${COEK_HOME}/include -L${COEK_HOME}/lib/ -lcoek

