all:
	- cd acpower; make
	- cd clnlbeam; make
	- cd fac; make
	- cd lqcp; make

gurobi:
	- cd acpower; make gurobi
	- cd clnlbeam; make gurobi
	- cd fac; make gurobi
	- cd lqcp; make gurobi

coek:
	- cd acpower; make coek
	- cd clnlbeam; make coek
	- cd fac; make coek
	- cd lqcp; make coek

clean:
	- cd acpower; make clean; cd ..
	- cd clnlbeam; make clean; cd ..
	- cd fac; make clean; cd ..
	- cd lqcp; make clean; cd ..
