
pmedian: pmedian.cpp
	c++ -O2 pmedian.cpp -o pmedian -I$GUROBI_HOME/include -L$GUROBI_HOME/lib/ -lgurobi_c++ -lgurobi81

pmeidan_coek: pmedian_coek.cpp
	c++ -std=c++11 -O2 pmedian_coek.cpp -o pmedian_coek -I${COEK_HOME}/include -L${COEK_HOME}/lib/ -lcoek

